### ISSUE TITLE
"The selected structure is not available offline" error

### ISSUE THREAD

**Issue by Anrock** [JuanJakobo/Pocketbook-Nextcloud-Client#17]
Hello. PocketBook 740, app version 0.73.

After filling in the fields on login page and pressing "Login" button it shows hourglass for a second and then the "The selected structure is not available offline" error.

Device is connected to Wifi and I can load pages in builtin browser no problem.

One weird thing I've noticed is that when using your app wifi icon in header was "empty". After launching a browser and loading a page wifi icon became "filled". But after I've switched back to app and tried login again - same error appeared. However after I've used "close app" in the app menu and launched it again - login was succesful and I saw my files.

Seems like there is some kind of energy preserving feature that turns wifi off if it's not used and it detects that browser needs wifi and enables it but doesn't work for your app. 

Thanks for the app, by the way!

**Comment by JuanJakobo** [comment]
Hey, 

sorry for the delayed response. The app calls a method called "Util::connectToNetwork" and this one checks if internet access is available. Was only the message "The selected structure is not available offline" showed or also an other error message?

Is the app working for you by now?

Thanks for the feedback :) the problem is that I am almost no longer using the app...

**Comment by Anrock** [comment]
Only "The selected structure is not available offline" was shown, no other errors.

I've managed to make it working by launching builtin browser and then relaunching the app.
